title = "中国金融学年会"
baseURL = "https://danielyang1009.github.io/cfam/"
languageCode = "zh-CN"
theme = "gohugo-theme-ananke"
# themesDir = "../.."
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh-CN"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
# enableRobotsTXT = true

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

[params]
#   favicon = ""
#   description = ""
#   facebook = ""
#   twitter = ""
#   instagram = ""
#   youtube = ""
#   github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "images/bg.png"
  recent_posts_number = 2
